apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secret-store
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: yc-auth
          key: authorized-key
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: {{ backend_service_name }}-backend # the target k8s secret name
  data:
    - secretKey: DATABASE_URL # the target k8s secret key
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: DATABASE_URL  # select a specific property of the Provider value (if a map)
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: REDIS_PASSWORD
    - secretKey: REDIS_HOST
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: REDIS_HOST
    - secretKey: REDIS_PORT
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: REDIS_PORT
    - secretKey: REDIS_SSL
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: REDIS_SSL
    - secretKey: DJANGO_SECRET_KEY
      remoteRef:
        key: {{ yandex_lockbox_secret_id }}
        property: DJANGO_SECRET_KEY
    - secretKey: DJANGO_DB_SECRET_KEY
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: DJANGO_DB_SECRET_KEY
    - secretKey: DJANGO_EMAIL_HOST_PASSWORD
      remoteRef:
        key: {{ yandex_lockbox_secret_id }}
        property: DJANGO_EMAIL_HOST_PASSWORD
    - secretKey: SOCIAL_AUTH_YANDEXRU_SECRET
      remoteRef:
        key: {{ yandex_lockbox_secret_id }}
        property: SOCIAL_AUTH_YANDEXRU_SECRET
    - secretKey: HASHIDS_SALT
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: LMS_HASHIDS_SALT
    # Simple Email Service
    - secretKey: AWS_SES_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ yandex_lockbox_secret_id }}
        property: YDS_AWS_SES_SECRET_ACCESS_KEY
    # Yandex Storage
    - secretKey: AWS_S3_REGION_NAME
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: YC_S3_REGION_NAME
    - secretKey: AWS_S3_ENDPOINT_URL
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: YC_S3_ENDPOINT_URL
    - secretKey: AWS_S3_ACCESS_KEY_ID
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: YC_S3_ACCESS_KEY_ID
    - secretKey: AWS_S3_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: YC_S3_SECRET_ACCESS_KEY
    # Yandex.Disk
    - secretKey: YANDEX_DISK_PASSWORD
      remoteRef:
        key: {{ yandex_lockbox_secret_id }}
        property: YANDEX_DISK_PASSWORD
    - secretKey: YANDEX_DISK_CLIENT_SECRET
      remoteRef:
        key: {{ yandex_lockbox_secret_id }}
        property: YANDEX_DISK_CLIENT_SECRET
    - secretKey: YANDEX_DISK_ACCESS_TOKEN
      remoteRef:
        key: {{ yandex_lockbox_secret_id }}
        property: YANDEX_DISK_ACCESS_TOKEN
    - secretKey: YANDEX_DISK_REFRESH_TOKEN
      remoteRef:
        key: {{ yandex_lockbox_secret_id }}
        property: YANDEX_DISK_REFRESH_TOKEN
    # Social auth
    - secretKey: SOCIAL_AUTH_GITLAB_MANYTASK_KEY
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: SOCIAL_AUTH_GITLAB_MANYTASK_KEY
    - secretKey: SOCIAL_AUTH_GITLAB_MANYTASK_SECRET
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: SOCIAL_AUTH_GITLAB_MANYTASK_SECRET
    - secretKey: LDAP_CLIENT_PASSWORD
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: LDAP_CLIENT_PASSWORD
    - secretKey: LDAP_CA_CERT_FILE
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: LDAP_CA_CERT_FILE
    - secretKey: GERRIT_CLIENT_HTTP_PASSWORD
      remoteRef:
        key: {{ shared_lockbox_secret_id }}
        property: GERRIT_CLIENT_HTTP_PASSWORD
    - secretKey: RECAPTCHA_PRIVATE_KEY
      remoteRef:
        key: {{ yandex_lockbox_secret_id }}
        property: RECAPTCHA_PRIVATE_KEY
    - secretKey: SOCIAL_AUTH_GITHUB_SECRET
      remoteRef:
        key: {{ yandex_lockbox_secret_id }}
        property: SOCIAL_AUTH_GITHUB_SECRET
