name: lms

services:
  webpack-bundles:
    build:
      context: .
      dockerfile: docker-files/static/Dockerfile
      args:
        - WEBPACK_ENVIRONMENT=prod
        - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
    image: lms-webpack-bundles
    command: /bin/true
  backend-base:
    build:
      context: .
      dockerfile: docker-files/app/common.Dockerfile
    image: lms-backend-base
    command: /bin/true
  backend:
    build:
      context: .
      dockerfile: docker-files/app/Dockerfile
      args:
        - BASE_IMAGE=lms-backend-base
        - FRONTEND_IMAGE=lms-webpack-bundles
        - DJANGO_STATIC_ROOT=/var/www/static/
        - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
    image: lms-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://csc:FooBar@db:5432/cscdb
      - PROJECT_MODULE_NAME=site_ru
      - REDIS_HOST=lms-redis-cluster
      - REDIS_PASSWORD=secret-password
    volumes:
      - static-data:/var/www/static
    depends_on:
      - db
      - redis
      - backend-base
  backend-dev:
    build:
      context: .
      dockerfile: docker-files/app/dev.Dockerfile
      args:
        - BASE_IMAGE=lms-backend-base
    image: lms-backend-dev
    environment:
     - PROJECT_MODULE_NAME=site_ru
     - REDIS_HOST=lms-redis-cluster
     - REDIS_PASSWORD=secret-password
    depends_on:
      - db
      - redis
      - backend
  task-worker:
    image: lms-backend
    restart: always
    environment:
      - DEBUG=0
      - REDIS_HOST=lms-redis-cluster
      - REDIS_PASSWORD=secret-password
    command: python manage.py rqworker high default
    depends_on:
      - backend
  nginx:
    build:
      context: ./docker-files/nginx
      dockerfile: Dockerfile
    image: lms-backend-nginx
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - static-data:/var/www/static
      - media-data:/var/www/media
    depends_on:
      - redis
      - backend
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: csc
      POSTGRES_DB: cscdb
      POSTGRES_PASSWORD: FooBar
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  redis:
    image: "redis:6-alpine"
    command: sh -c 'if [ "x$${REDIS_PASSWORD}" = "x" ]; then redis-server --appendonly yes; else redis-server --appendonly yes --requirepass $$REDIS_PASSWORD; fi'
    expose:
      - 6379
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=secret-password

volumes:
  static-data:
  media-data:
    name: lms-media
    external: true
  redis-data:
  postgres-data:
