apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{{ k8s_namespace}}"
  name: "scheduler"
spec:
  replicas: 1
  revisionHistoryLimit: {{ revision_history_limit | default('3') }}
  selector:
    matchLabels:
      app: "scheduler"
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: "scheduler"
        alias: "cronjob"
    spec:
      terminationGracePeriodSeconds: {{ termination_grace_period_seconds | default('30') }}
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: worker
          image: "{{ docker_registry }}/{{ backend_django_image_name }}:{{ backend_django_image_tag }}"
          lifecycle:
            preStop:
              exec:
                command: [ '/bin/sh', '-c', 'sleep 5' ]
          command: ["/bin/sh"]
          args: ["-c", "rqscheduler --host $(REDIS_HOST) --password $(REDIS_PASSWORD) --port $(REDIS_PORT) --db $(REDIS_DB) --interval 10"]
          resources:
            requests:
              cpu: 50m  # 5% of 1 vCPU
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          env:
            {% filter indent(width=12) %}{% include 'app-env.yaml' %}{% endfilter %}
